Config = {
  Locale = "fr",

  UseMetabolism = false, -- Experimental Function

  -- Status amount rate drop
  EveryTimeStatusDown = 25000, --  3,6 seconds
  HowAmountThirstWhileRunning = 3, -- Example drop 3 every 3,6 seconds -- Max value 1000
  HowAmountHungerWhileRunning = 3,
  HowAmountThirst = 2,
  HowAmountHunger = 2,
  HowAmountMetabolismWhileRunning = 2,
  HowAmountMetabolism = 2,

  FirstHungerStatus = 1000, -- 100%
  FirstThirstStatus = 1000, -- 100%

  OnRespawnHungerStatus = 1000,
  OnRespawnThirstStatus = 1000,

  FirstMetabolismStatus = 0,


-------------------------------------------------------------------------------------------------
----------------------------------------------           ITEMS         --------------------------
-------------------------------------------------------------------------------------------------

ItemsToUse = {
    {
      Name = "beer",
      Thirst = 0,
      Hunger = -50,  
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0.0,
      OuterCoreHealthGold = 0.0,
      InnerCoreStaminaGold = 0.0,
      OuterCoreStaminaGold = 0.0,
      PropName = "",
      Animation = "beer"
    },
    {
      Name = "whisky",
      Thirst = 0,
      Hunger = -50, 
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0.0,
      OuterCoreHealthGold = 0.0,
      InnerCoreStaminaGold = 0.0,
      OuterCoreStaminaGold = 0.0,
      PropName = "p_bottlesnakeoil_cs01x",
      Animation = "whisky"
    },
    {
      Name = "shampan",
      Thirst = 0,
      Hunger = -50, 
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0.0,
      OuterCoreHealthGold = 0.0,
      InnerCoreStaminaGold = 0.0,
      OuterCoreStaminaGold = 0.0,
      PropName = "",
      Animation = "shampan"
    },

    {
      Name = "volaille",
      Thirst = -5,
      Hunger = 50,
      Metabolism = 20,
      Stamina = 50,
      InnerCoreHealth = 0,
      OuterCoreHealth = -50,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_chickenhalf02x",
      Animation = "eat"
    },
    {
      Name = "volaillerotie",
      Thirst = -15,
      Hunger = 100,
      Metabolism = 20,
      Stamina = 10,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },
    {
      Name = "poisson",
      Thirst = -5,
      Hunger = 50,
      Metabolism = 20,
      Stamina = 10,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },

    {
      Name = "poissongrille",
      Thirst = -5,
      Hunger = 100,
      Metabolism = 20,
      Stamina = 20,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },
    {
      Name = "viandepetitgibier",
      Thirst = -5,
      Hunger = 50,
      Metabolism = 20,
      Stamina = 5,
      InnerCoreHealth = 0,
      OuterCoreHealth = -50,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_cs_meatstewsmall01x",
      Animation = "eat"
    },
    {
      Name = "petitgibiergrille",
      Thirst = -15,
      Hunger = 100,
      Metabolism = 20,
      Stamina = 20,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },
    {
      Name = "viandegibier",
      Thirst = -5,
      Hunger = 50,
      Metabolism = 20,
      Stamina = 5,
      InnerCoreHealth = 0,
      OuterCoreHealth = -50,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_cs_meatstewsmall01x",
      Animation = "eat"
    },
    {
      Name = "gibiergrille",
      Thirst = -5,
      Hunger = 100,
      Metabolism = 20,
      Stamina = 20,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },
    {
      Name = "viandegrosgibier",
      Thirst = -5,
      Hunger = 50,
      Metabolism = 20,
      Stamina = 5,
      InnerCoreHealth = 0,
      OuterCoreHealth = -50,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_cs_meatstewsmall01x",
      Animation = "eat"
    },
    {
      Name = "grosgibiergrille",
      Thirst = -25,
      Hunger = 100,
      Metabolism = 20,
      Stamina = 20,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_main_prairiechicken01x",
      Animation = "eat"
    },
    {
      Name = "tomato",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_apple02x",
      Animation = "eat"
    },
    {
      Name = "carrot",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_carrot01x",
      Animation = "eat"
    },
    {
      Name = "lettuce",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "s_lettuce01x",
      Animation = "eat"
    },
    {
      Name = "potato",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_potato01x",
      Animation = "eat"
    },
    {
      Name = "orange",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "s_bit_apple01x",
      Animation = "eat"
    },
    {
      Name = "raisin",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "s_inv_raspberry01bx",
      Animation = "eat"
    },
    {
      Name = "pomme",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "s_bit_apple01x",
      Animation = "eat"
    },
    {
      Name = "corn",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_corn02x",
      Animation = "eat"
    },
    {
      Name = "betterave",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_beet_01x",
      Animation = "eat"
    },
    {
      Name = "haricot",
      Thirst = 0,
      Hunger = 10,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "s_inv_raspberry01bx",
      Animation = "eat"
    },
    {
      Name = "ragout",
      Thirst = -20,
      Hunger = 250,
      Metabolism = 25,
      Stamina = 25,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_bowl04x_stew",
      Animation = "eatbowl"
    },
    {
      Name = "chili",
      Thirst = -20,
      Hunger = 250,
      Metabolism = 25,
      Stamina = 25,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_bowl04x_stew",
      Animation = "eatbowl"
    },
    {
      Name = "consumable_coffee",
      Thirst = 100,
      Hunger = -10,
      Metabolism = 50,
      Stamina = 50,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 250,
      OuterCoreStaminaGold = 0,
      PropName = "p_mugcoffee01x",
      Animation = "coffe"
    },
    {
      Name = "soupepoisson",
      Thirst = -20,
      Hunger = 250,
      Metabolism = 25,
      Stamina = 25,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_fishstew01x",
      Animation = "eatbowl"
    },
    {
      Name = "soupelegumes",
      Thirst = -20,
      Hunger = 250,
      Metabolism = 25,
      Stamina = 25,
      InnerCoreHealth = 0,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_bowl04x_stew",
      Animation = "eatbowl"
    },
    {
      Name = "bandage",
      Thirst = 0,
      Hunger = 0,
      Metabolism = 0,
      Stamina = 0,
      InnerCoreHealth = 15,
      OuterCoreHealth = 0,
      InnerCoreHealthGold = 0,
      OuterCoreHealthGold = 0,
      InnerCoreStaminaGold = 0,
      OuterCoreStaminaGold = 0,
      PropName = "p_bowl04x_stew",
      Animation = "eatbowl"
    },
  }

}

Translations = {
  ['fr'] = {
    ['OnUseItem'] =  "Consommé: %s"
  },
}
